import type { Metadata } from "next";

import { GeistSans } from "geist/font/sans";

import "@/styles/globals.css";

import { cn } from "@/utils/cn";

import { Footer } from "@/components/ui/Footer";

export const metadata: Metadata = {
  title: {
    default: "Luxe",
    template: "%s · Luxe",
  },
  description: "Generated by create next app",
  icons: {
    apple: "/favicon.svg",
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "font-sans antialiased outline-none bg-background text-foreground",
          GeistSans.variable
        )}
      >
        <div className="mx-auto max-w-6xl w-full px-4">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
